<?php

/*
 * override template_preprocess_jplayer_view_playlist
 */
function jplayer_retheme_preprocess_jplayer_view_playlist(&$vars)
{
  $view = $vars['view'];
  $vars['settings'] = $view->style_plugin->options;
  $vars['mode'] = 'playlist';
  $vars['player_id'] = _jplayer_check_id('jplayer-view-' . str_replace('_', '-', check_plain($view->name)));

  foreach ($vars['items'] as $delta => $item)
  {
    $views_fields = explode("\n", trim($item['label']));
    $vars['items'][$delta]['label'] = trim(strip_tags(array_shift($views_fields)));
    foreach ($views_fields AS $vf)
    {
      $vf = trim($vf);
      if ($vf) { $vars['items'][$delta]['views_fields'][] = $vf; }
    }
  }
  $player = jplayer_retheme_sort_files($vars['items'], $vars['player_id'], $vars['mode']);

  $vars['playlist'] = theme('jplayer_item_list', array('items' => $player['playlist']));
  $vars['type'] = $player['type'];
  // Add player settings
  $player = array(
    'jplayerInstances' => array(
      $vars['player_id'] => array(
        'files' => $player['files'],
        'solution' => $vars['settings']['solution'],
        'supplied' => $player['extensions'],
        'preload' => $vars['settings']['preload'],
        'volume' => $vars['settings']['volume'] / 100,
        'muted' => (boolean)$vars['settings']['muted'],
        'autoplay' => (boolean)$vars['settings']['autoplay'],
        'repeat' => $vars['settings']['repeat'],
        'backgroundColor' => $vars['settings']['backgroundColor'],
      ),
    ),
  );
  drupal_add_js($player, 'setting');

  $vars['dynamic'] = jplayer_add_core_js();
} // jplayer_retheme_preprocess_jplayer_view_playlist */

/*
 * alternate to jplayer_sort_files
 */
function jplayer_retheme_sort_files($raw_files = array(), $player_id, $type = 'single') {
  $video_extensions = array('m4v', 'mp4', 'ogv', 'webmv');
  $audio_extensions = array('mp3', 'm4a', 'oga', 'webma', 'wav');
  $poster_extensions = array('jpg', 'jpeg', 'png', 'gif');

  $poster = NULL;
  $videos = FALSE;
  $audio = FALSE;
  $media = array();

  $files = array();
  $extensions = array();
  $playlist = array();

  // Look through all the files provided and see what we have
  foreach ($raw_files as $delta => $item) {
    // Get file URL
    if (!isset($item['url'])) {
      $item['url'] = file_create_url($item['uri']);
    }

    // Get file extension
    if (!isset($item['ext'])) {
      $fileinfo = pathinfo($item['url']);
      $item['ext'] = $fileinfo['extension'];
    }

    // Get file label
    if (!isset($item['label'])) {
      if (empty($item['description'])) {
        $item['label'] = $item['filename'];
      }
      else {
        $item['label'] = $item['description'];
      }
    }
    // Add file into correct group
    if (in_array($item['ext'], $video_extensions)) {
      $videos = TRUE;
      $item['type'] = 'audio';
    }
    elseif (in_array($item['ext'], $audio_extensions)) {
      $audio = TRUE;
      $item['type'] = 'video';
    }
    elseif (in_array($item['ext'], $poster_extensions)) {
      $poster = $item['url'];
      $item['type'] = 'poster';
    }

    $media[] = $item;
  }
  $num = 0;
  foreach ($media as $file) {
    if ($videos == TRUE && $type != 'playlist') {
      if ($file['type'] == 'audio') {
        unset($file);
      }
      $player_type = 'video';
    }
    elseif ($videos == TRUE && $type == 'playlist') {
      $player_type = 'video';
    }
    else {
      $player_type = 'audio';
    }
    if (isset($file) && $file['type'] == 'audio') {
      $files[][$file['ext']] = $file['url'];
      $extensions[] = $file['ext'];
      $row = l($file['label'], $file['url'], array('attributes' => array('id' => $player_id . '_item_' . $num, 'tabindex' => 1), 'html' => TRUE));
      foreach ($file['views_fields'] AS $field)
      {
        $row .= "\n".$field;
      }
      $playlist[] = $row;
      $num++;
    }
    elseif (isset($file) && $file['type'] == 'video') {
      $files[][$file['ext']] = $file['url'];
      if ($poster != NULL) {
        $files[]['poster'] = $poster;
      }
      $extensions[] = $file['ext'];
      $row = l($file['label'], $file['url'], array('attributes' => array('id' => $player_id . '_item_' . $num, 'tabindex' => 1), 'html' => TRUE));
      foreach ($file['views_fields'] AS $field)
      {
        $row .= "\n".$field;
      }
      $playlist[] = $row;
      $num++;
    }
  }
  if ($type == 'single') {
    $item = array_shift($playlist);
    $playlist = array();
    $playlist[] = $item;
  }

  return array('files' => $files, 'extensions' => implode(',', $extensions), 'playlist' => $playlist, 'type' => $player_type);
} // jplayer_retheme_sort_files
