<?php
/**
 * @file
 * directory.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function directory_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-directory_person-body'
  $field_instances['node-directory_person-body'] = array(
    'bundle' => 'directory_person',
    'default_value' => array(
      0 => array(
        'summary' => '',
        'value' => '',
        'format' => 'full_html',
      ),
    ),
    'deleted' => 0,
    'description' => 'Provide as much or as little biographical information as preferred.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 6,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(
          'trim_length' => 600,
        ),
        'type' => 'text_summary_or_trimmed',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'body',
    'label' => 'Biography',
    'required' => 0,
    'settings' => array(
      'display_summary' => 0,
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 20,
        'summary_rows' => 5,
      ),
      'type' => 'text_textarea_with_summary',
      'weight' => 31,
    ),
  );

  // Exported field_instance: 'node-directory_person-field_dp_email_address'
  $field_instances['node-directory_person-field_dp_email_address'] = array(
    'bundle' => 'directory_person',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Please note that adding an email address here will result in a link to email the person when they are viewed on the site. This is a potential source of spam, so carefully consider whether or not to provide this information.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'email',
        'settings' => array(),
        'type' => 'email_contact',
        'weight' => 3,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_dp_email_address',
    'label' => 'Email Address',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'email',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'email_textfield',
      'weight' => 36,
    ),
  );

  // Exported field_instance: 'node-directory_person-field_dp_first'
  $field_instances['node-directory_person-field_dp_first'] = array(
    'bundle' => 'directory_person',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 7,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_dp_first',
    'label' => 'First',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 32,
    ),
  );

  // Exported field_instance: 'node-directory_person-field_dp_hours'
  $field_instances['node-directory_person-field_dp_hours'] = array(
    'bundle' => 'directory_person',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Provide the hours that the person is present in their office, if applicable. Example:<br>
Monday - Friday: 8 AM CT - 5 PM CT<br>
Saturday: 8 AM CT - 12 PM CT<br>
Sunday: Not in office',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 5,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_dp_hours',
    'label' => 'Hours',
    'required' => 0,
    'settings' => array(
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 38,
    ),
  );

  // Exported field_instance: 'node-directory_person-field_dp_job_role'
  $field_instances['node-directory_person-field_dp_job_role'] = array(
    'bundle' => 'directory_person',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Provide the job role or title of the person.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_dp_job_role',
    'label' => 'Job Role',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 37,
    ),
  );

  // Exported field_instance: 'node-directory_person-field_dp_last'
  $field_instances['node-directory_person-field_dp_last'] = array(
    'bundle' => 'directory_person',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 9,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_dp_last',
    'label' => 'Last',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 34,
    ),
  );

  // Exported field_instance: 'node-directory_person-field_dp_location'
  $field_instances['node-directory_person-field_dp_location'] = array(
    'bundle' => 'directory_person',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'You can add multiple locations, and you need only enter the relevant information for each location.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'location_cck',
        'settings' => array(),
        'type' => 'location_default',
        'weight' => 4,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_dp_location',
    'label' => 'Location',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'location_cck',
      'settings' => array(),
      'type' => 'location',
      'weight' => 37,
    ),
  );

  // Exported field_instance: 'node-directory_person-field_dp_middle'
  $field_instances['node-directory_person-field_dp_middle'] = array(
    'bundle' => 'directory_person',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Provide middle name or middle initial.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 8,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_dp_middle',
    'label' => 'Middle',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 33,
    ),
  );

  // Exported field_instance: 'node-directory_person-field_dp_photo'
  $field_instances['node-directory_person-field_dp_photo'] = array(
    'bundle' => 'directory_person',
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'image',
        'settings' => array(
          'image_link' => '',
          'image_style' => 'medium',
        ),
        'type' => 'image',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_dp_photo',
    'label' => 'Photo',
    'required' => 0,
    'settings' => array(
      'alt_field' => 0,
      'default_image' => 0,
      'file_directory' => 'directory_person/photos',
      'file_extensions' => 'png gif jpg jpeg',
      'max_filesize' => '',
      'max_resolution' => '',
      'min_resolution' => '',
      'title_field' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'media',
      'settings' => array(
        'allowed_schemes' => array(
          'private' => 'private',
          'public' => 'public',
        ),
        'allowed_types' => array(
          'audio' => 0,
          'default' => 0,
          'image' => 'image',
          'video' => 0,
        ),
        'browser_plugins' => array(
          'library' => 0,
          'media_default--media_browser_1' => 0,
          'upload' => 0,
        ),
        'progress_indicator' => 'throbber',
      ),
      'type' => 'media_generic',
      'weight' => 38,
    ),
  );

  // Exported field_instance: 'node-directory_person-field_dp_type'
  $field_instances['node-directory_person-field_dp_type'] = array(
    'bundle' => 'directory_person',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Provide a grouping for this person, and it will be shown that way on the site.',
    'display' => array(
      'default' => array(
        'label' => 'inline',
        'module' => 'taxonomy',
        'settings' => array(),
        'type' => 'taxonomy_term_reference_plain',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'fences_wrapper' => 'h2',
    'field_name' => 'field_dp_type',
    'label' => 'Type',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 1,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Biography');
  t('Email Address');
  t('First');
  t('Hours');
  t('Job Role');
  t('Last');
  t('Location');
  t('Middle');
  t('Photo');
  t('Please note that adding an email address here will result in a link to email the person when they are viewed on the site. This is a potential source of spam, so carefully consider whether or not to provide this information.');
  t('Provide a grouping for this person, and it will be shown that way on the site.');
  t('Provide as much or as little biographical information as preferred.');
  t('Provide middle name or middle initial.');
  t('Provide the hours that the person is present in their office, if applicable. Example:<br>
Monday - Friday: 8 AM CT - 5 PM CT<br>
Saturday: 8 AM CT - 12 PM CT<br>
Sunday: Not in office');
  t('Provide the job role or title of the person.');
  t('Type');
  t('You can add multiple locations, and you need only enter the relevant information for each location.');

  return $field_instances;
}
