<?php

function mcn_circleten_menu() {
  $items['yyouth'] = array(
    'title' => 'Set a sticky session value',
    'page callback' => 'set_sticky_youth',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['pparent'] = array(
    'title' => 'Set a sticky session value',
    'page callback' => 'set_sticky_parent',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['vvolunteer'] = array(
    'title' => 'Set a sticky session value',
    'page callback' => 'set_sticky_volunteer',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['ssupporter'] = array(
    'title' => 'Set a sticky session value',
    'page callback' => 'set_sticky_supporter',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function set_sticky_youth() {
  $_SESSION['sticky_youth'] = 1;
  unset($_SESSION['sticky_volunteer']);
  unset($_SESSION['sticky_parent']);
  unset($_SESSION['sticky_supporter']);
  drupal_goto('youth');
}
function set_sticky_parent() {
  unset($_SESSION['sticky_youth']);
  unset($_SESSION['sticky_volunteer']);
  $_SESSION['sticky_parent'] = 1;
  unset($_SESSION['sticky_supporter']);
  drupal_goto('parent');
}
function set_sticky_volunteer() {
  unset($_SESSION['sticky_youth']);
  $_SESSION['sticky_volunteer'] = 1;
  unset($_SESSION['sticky_parent']);
  unset($_SESSION['sticky_supporter']);
  drupal_goto('volunteer');
}
function set_sticky_supporter() {
  unset($_SESSION['sticky_youth']);
  unset($_SESSION['sticky_volunteer']);
  unset($_SESSION['sticky_parent']);
  $_SESSION['sticky_supporter'] = 1;
  drupal_goto('supporter');
}

